name = "LMGPU"
uuid = "80ae3f88-c08a-44f8-80fe-4bd6150eb394"
authors = ["Chelsea Trotter", "Sen Research"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.3"
Documenter = "0.24"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["Test"]
